# Generated by Django 5.0.7 on 2024-08-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
